# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "284a0aa97c9539e1958449727c3dd4ee"
name = "Discount On Tag"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "discount-on-tag"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
