api_version = "2026-01"
[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
description = "t:description"
handle = "smart-discount-ui"
uid = "b4070182-0174-2b51-ddd4-788b17fa545824ea4fb8"
type = "ui_extension"
# Only 1 target can be specified for each Admin block extension
[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.jsx"
target = "admin.discount-details.function-settings.render"

[[extensions.metafields]]
namespace = "$app"
key = "function-configuration"


